### ISSUE TITLE
Rename to farm_precipitation

### ISSUE THREAD

**Issue by jgaehring** [jgaehring/farm_precipitation#1]
We've talked about the issue of this module being named the same as the quick form, also named `farm_weather`, and I was wondering what y'all think about renaming it `farm_precipitation` or `farm_precip`, either temporarily to avoid collision while we migrate over from quick forms to field modules, or permanently. I think it might actually be a more appropriate name, since it's not really recording any other weather data.

Dunno if there was intention to do more in the future, but frankly, I like the simplicity of just recording precipitation (do farmers ever need to record wind speed or barometric pressure?). Especially for a field module, I think that simplicity is paramount. I'll say right now what I _don't_ want it to become is another app for getting weather reports from the NWS; there are enough of those in the world as it is, and I don't hope to persuade farmers to switch from their current favorite weather app.

cc: @mstenta, @paul121

**Comment by mstenta** [comment]
Fine with me!

One small idea to consider: what about `farm_weather_precip`?

That would allow it to potentially become a sub-module of `farm_weather` very easily without any namespace conflicts or changes needed.  It means a longer namespace in the short-term though.

**Comment by jgaehring** [comment]
Oh, yea, I didn't realize that, but that might be good. I don't so much mind the long namespace, since it won't come into play in the JS code.

**Comment by jgaehring** [comment]
I decided to just stick with `farm_precipitation` in cc13b3f. I'm not sure what benefits there would be to making this a sub-module, but I prefer to err to the side of less coupling with other modules, especially early on when, like I said, I'm not even sure if there are any benefits to it. It just seems like a premature design choice to me.
